### ISSUE TITLE
add CMake build system?

### ISSUE THREAD

**Issue by ghost** [facebook/libafdt#1]
hhvm added a CMake based build system as seen here: https://github.com/hhvm/hhvm-third-party/tree/master/libafdt

Should it be used mostly as is? or at all? should it replace the current one?

**Comment by dreiss** [comment]
I'd be okay with adding CMake in addition to autotools, but I don't want to delete the existing files.

**Comment by ghost** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dreiss** [comment]
I'm going to close this issue for now because we have no plans to implement it internally.  If a pull request shows up, I'll probably accept it.
